### ISSUE TITLE
Error running code

### ISSUE THREAD

**Issue by zeeshan1001** [agebrock/inject-tunnel-ssh#1]
With the code below I get an error:

require('inject-tunnel-ssh')([config.network.tunnelConfigs]).on('error', function() {
        throw new Error('Error creating tunnel');
    });

ERROR:

module.js:327
    throw err;
    ^

Error: Cannot find module 'debug'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\ecommerce\PerformanceInit\Dashboard\node_modules\inject-tunnel-ssh\lib\port.js:2:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\ecommerce\PerformanceInit\Dashboard\node_modules\inject-tunnel-ssh\lib\index.js:5:35)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)

Process finished with exit code 1

**Comment by agebrock** [comment]
Ah yes i see the module is missing but should come with the tunnel-ssh, but indeed that should be changed. 

Are you still using npm2 ?

**Comment by agebrock** [comment]
Please update to version 0.0.5. Thx for the reporting !
